name: CI

on:
  push:
    branches:
      - dk/dockerization-pipeline

permissions:
  contents: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      VERSION_MAJOR_MINOR: ${{ vars.VERSION_MAJOR_MINOR }}
      VERSION_PATCH: ${{ vars.VERSION_PATCH }}
      GITHUB_TOKEN_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute version
        id: version
        run: |
          # Major/Minor aus Repo-Variable
          MAJOR=$(echo $VERSION_MAJOR_MINOR | cut -d. -f1)
          MINOR=$(echo $VERSION_MAJOR_MINOR | cut -d. -f2)

          # Patch hochzählen
          PATCH=$((VERSION_PATCH + 1))

          # Version korrekt zusammensetzen
          VERSION="$MAJOR.$MINOR.$PATCH"

          # Git Hash
          GIT_HASH=$(git rev-parse --short HEAD)

          echo "Computed Version: $VERSION"
          echo "Patch: $PATCH"
          echo "Git Hash: $GIT_HASH"

          # Outputs setzen
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT
          echo "hash=$GIT_HASH" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: |
            engineeringmethodsag/fluid-asset-connector-python:latest
            engineeringmethodsag/fluid-asset-connector-python:${{ steps.version.outputs.version }}
            engineeringmethodsag/fluid-asset-connector-python:${{ steps.version.outputs.version }}-${{ steps.version.outputs.hash }}

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git tag
